### ISSUE TITLE
1.0 release on Maven Central?

### ISSUE THREAD

**Issue by jits** [malensek/jbsdiff#3]
Would it be possible to make a 1.0 release build (i.e. not a `SNAPSHOT`), and push it to Maven Central (http://search.maven.org/) ?

**Comment by malensek** [comment]
That's a good idea. I'll see if I can get this done in the next couple of days.

**Comment by jits** [comment]
@malensek – that would be much appreciated :smiley:

**Comment by malensek** [comment]
This is now available:

<dependency>
  <groupId>io.sigpipe</groupId>
  <artifactId>jbsdiff</artifactId>
  <version>1.0</version>
</dependency>

I am really sorry the process took so long. This was my first attempt at getting something added to Maven Central so I had a bit of reading to do...

**Comment by jits** [comment]
That's great – thanks very much for doing this :)
